# Generated by Django 4.2 on 2023-04-18 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urldispatcher', '0002_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentForm',
        ),
    ]
