# Generated by Django 4.2 on 2023-04-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urldispatcher', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='auth_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.CharField(default=1234567890, max_length=6),
            preserve_default=False,
        ),
    ]
