# Generated by Django 4.2 on 2023-04-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urldispatcher', '0006_remove_profile_otp_alter_profile_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forgot_password_token',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
