# Generated by Django 4.2 on 2023-04-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urldispatcher', '0008_rename_forgot_password_token_profile_auth_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forget_password_token',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
