# Generated by Django 4.2 on 2023-04-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urldispatcher', '0009_profile_forget_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.CharField(default='SOME STRING', max_length=6),
        ),
    ]
