# Generated by Django 4.2 on 2023-04-26 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urldispatcher', '0010_profile_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='otp',
        ),
    ]
