# Generated by Django 4.2 on 2023-04-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urldispatcher', '0013_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='Add image url which is you want', upload_to=''),
        ),
    ]
