# Generated by Django 4.2 on 2023-04-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urldispatcher', '0014_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
