# Generated by Django 4.2 on 2023-05-01 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urldispatcher', '0016_payment_remove_book_order_id_remove_book_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='price',
            new_name='amount',
        ),
    ]
